In [90]:
import pandas as pd

In [91]:
data=pd.read_excel("Telco-Customer-Churn.xlsx")
data

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
...          ...     ...            ...  ...            ...          ...    ...
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[7043 rows x 21 columns]

In [92]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [93]:
data.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95      1889.50     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

1. a. Gender

In [94]:
data["gender"].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

In [95]:
data["Churn"]=="No"

0        True
1        True
2       False
3        True
4       False
        ...
7038     True
7039     True
7040     True
7041    False
7042     True
Name: Churn, Length: 7043, dtype: bool

In [96]:
d1=data[data["Churn"]=="No"]
d1

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
6     1452-KIOVK    Male              0  ...          89.10      1949.40     No
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
...          ...     ...            ...  ...            ...          ...    ...
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[5174 rows x 21 columns]

In [97]:
d1["gender"].value_counts()

Male      2625
Female    2549
Name: gender, dtype: int64

1. b. Citizenship

In [98]:
data["SeniorCitizen"].value_counts()

0    5901
1    1142
Name: SeniorCitizen, dtype: int64

In [99]:
d1["SeniorCitizen"].value_counts()

0    4508
1     666
Name: SeniorCitizen, dtype: int64

2. a. Gender

In [100]:
data["Churn"]=="Yes"

0       False
1       False
2        True
3       False
4        True
        ...
7038    False
7039    False
7040    False
7041     True
7042    False
Name: Churn, Length: 7043, dtype: bool

In [101]:
d2=data[data["Churn"]=="Yes"]
d2

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
13    0280-XJGEX    Male              0  ...         103.70      5036.30    Yes
...          ...     ...            ...  ...            ...          ...    ...
7021  1699-HPSBG    Male              0  ...          59.80       727.80    Yes
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7032  6894-LFHLY    Male              1  ...          75.75        75.75    Yes
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes

[1869 rows x 21 columns]

In [102]:
d2["gender"].value_counts()

Female    939
Male      930
Name: gender, dtype: int64

2. b. Citizenship

In [103]:
d2["SeniorCitizen"].value_counts()

0    1393
1     476
Name: SeniorCitizen, dtype: int64

3. a. Payment method based on churn

In [104]:
data["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [105]:
d1["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [106]:
d1["PaymentMethod"].value_counts()

Mailed check                 1304
Electronic check             1294
Credit card (automatic)      1290
Bank transfer (automatic)    1286
Name: PaymentMethod, dtype: int64

In [107]:
d2["PaymentMethod"].unique()

array(['Mailed check', 'Electronic check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [108]:
d2["PaymentMethod"].value_counts()

Electronic check             1071
Mailed check                  308
Bank transfer (automatic)     258
Credit card (automatic)       232
Name: PaymentMethod, dtype: int64

3. b. Payment method based on contract

In [109]:
data["Contract"].value_counts()

Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

In [110]:
data["Contract"]=="Month-to-month"

0        True
1       False
2        True
3       False
4        True
        ...
7038    False
7039    False
7040     True
7041     True
7042    False
Name: Contract, Length: 7043, dtype: bool

In [111]:
d3=data[data["Contract"]=="Month-to-month"]
d3

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
6     1452-KIOVK    Male              0  ...          89.10      1949.40     No
...          ...     ...            ...  ...            ...          ...    ...
7033  9767-FFLEM    Male              0  ...          69.50      2625.25     No
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7035  8456-QDAVC    Male              0  ...          78.70      1495.10     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes

[3875 rows x 21 columns]

In [112]:
d3["PaymentMethod"].value_counts()

Electronic check             1850
Mailed check                  893
Bank transfer (automatic)     589
Credit card (automatic)       543
Name: PaymentMethod, dtype: int64

In [113]:
data["Contract"]=="Two year"

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042     True
Name: Contract, Length: 7043, dtype: bool

In [114]:
d4=data[data["Contract"]=="Two year"]
d4

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
11    7469-LKBCI    Male              0  ...          18.95       326.80     No
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
17    9959-WOFKT    Male              0  ...         106.70      7382.25     No
23    3638-WEABW  Female              0  ...          59.90      3505.10     No
28    5248-YGIJN    Male              0  ...          90.25      6369.45     No
...          ...     ...            ...  ...            ...          ...    ...
7017  4807-IZYOZ  Female              0  ...          20.65      1020.75     No
7019  9710-NJERN  Female              0  ...          20.15       826.00     No
7028  9281-CEDRU  Female              0  ...          64.10      4326.25     No
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[1695 rows x 21 columns]

In [115]:
d4["PaymentMethod"].value_counts()

Credit card (automatic)      581
Bank transfer (automatic)    564
Mailed check                 382
Electronic check             168
Name: PaymentMethod, dtype: int64

In [116]:
data["Contract"]=="One year"

0       False
1        True
2       False
3        True
4       False
        ...
7038     True
7039     True
7040    False
7041    False
7042    False
Name: Contract, Length: 7043, dtype: bool

In [117]:
d5=data[data["Contract"]=="One year"]
d5

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
9     6388-TABGU    Male              0  ...          56.15      3487.95     No
12    8091-TTVAX    Male              0  ...         100.35      5681.10     No
16    8191-XWSZG  Female              0  ...          20.65      1022.95     No
...          ...     ...            ...  ...            ...          ...    ...
7022  7203-OYKCT    Male              0  ...         104.95      7544.30     No
7031  3605-JISKB    Male              1  ...          60.00      3316.10     No
7036  7750-EYXWZ  Female              0  ...          60.65       743.30     No
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No

[1473 rows x 21 columns]

In [118]:
d5["PaymentMethod"].value_counts()

Credit card (automatic)      398
Bank transfer (automatic)    391
Electronic check             347
Mailed check                 337
Name: PaymentMethod, dtype: int64

4. Internet service

In [119]:
data['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [120]:
data["gender"] == "Male"

0       False
1        True
2        True
3        True
4       False
        ...
7038     True
7039    False
7040    False
7041     True
7042     True
Name: gender, Length: 7043, dtype: bool

In [121]:
d1

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
6     1452-KIOVK    Male              0  ...          89.10      1949.40     No
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
...          ...     ...            ...  ...            ...          ...    ...
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[5174 rows x 21 columns]

In [122]:
d1[data["gender"] == "Male"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE   Male              0  ...          56.95      1889.50     No
3     7795-CFOCW   Male              0  ...          42.30      1840.75     No
6     1452-KIOVK   Male              0  ...          89.10      1949.40     No
9     6388-TABGU   Male              0  ...          56.15      3487.95     No
10    9763-GRSKD   Male              0  ...          49.95       587.45     No
...          ...    ...            ...  ...            ...          ...    ...
7031  3605-JISKB   Male              1  ...          60.00      3316.10     No
7033  9767-FFLEM   Male              0  ...          69.50      2625.25     No
7035  8456-QDAVC   Male              0  ...          78.70      1495.10     No
7038  6840-RESVB   Male              0  ...          84.80      1990.50     No
7042  3186-AJIEK   Male              0  ...         105.65      6844.50     No

[2625 rows x 21 columns]

Internet service by males based on churn = no

In [123]:
d6=d1[data["gender"] == "Male"]
d6

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE   Male              0  ...          56.95      1889.50     No
3     7795-CFOCW   Male              0  ...          42.30      1840.75     No
6     1452-KIOVK   Male              0  ...          89.10      1949.40     No
9     6388-TABGU   Male              0  ...          56.15      3487.95     No
10    9763-GRSKD   Male              0  ...          49.95       587.45     No
...          ...    ...            ...  ...            ...          ...    ...
7031  3605-JISKB   Male              1  ...          60.00      3316.10     No
7033  9767-FFLEM   Male              0  ...          69.50      2625.25     No
7035  8456-QDAVC   Male              0  ...          78.70      1495.10     No
7038  6840-RESVB   Male              0  ...          84.80      1990.50     No
7042  3186-AJIEK   Male              0  ...         105.65      6844.50     No

[2625 rows x 21 columns]

In [124]:
d6['InternetService'].value_counts

<bound method IndexOpsMixin.value_counts of 1               DSL
3               DSL
6       Fiber optic
9               DSL
10              DSL
           ...
7031            DSL
7033    Fiber optic
7035    Fiber optic
7038            DSL
7042    Fiber optic
Name: InternetService, Length: 2625, dtype: object>

In [125]:
data["gender"] == "Female"

0        True
1       False
2       False
3       False
4        True
        ...
7038    False
7039     True
7040     True
7041    False
7042    False
Name: gender, Length: 7043, dtype: bool

In [126]:
d1[data["gender"] == "Female"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
16    8191-XWSZG  Female              0  ...          20.65      1022.95     No
19    4183-MYFRB  Female              0  ...          90.05      1862.90     No
...          ...     ...            ...  ...            ...          ...    ...
7030  0871-OPBXW  Female              0  ...          20.05        39.25     No
7036  7750-EYXWZ  Female              0  ...          60.65       743.30     No
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No

[2549 rows x 21 columns]

Internet service by females based on churn = no

In [127]:
d7=d1[data["gender"] == "Female"]
d7

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
16    8191-XWSZG  Female              0  ...          20.65      1022.95     No
19    4183-MYFRB  Female              0  ...          90.05      1862.90     No
...          ...     ...            ...  ...            ...          ...    ...
7030  0871-OPBXW  Female              0  ...          20.05        39.25     No
7036  7750-EYXWZ  Female              0  ...          60.65       743.30     No
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No

[2549 rows x 21 columns]

In [128]:
d7['InternetService'].value_counts

<bound method IndexOpsMixin.value_counts of 0               DSL
7               DSL
15      Fiber optic
16               No
19      Fiber optic
           ...
7030             No
7036            DSL
7037             No
7039    Fiber optic
7040            DSL
Name: InternetService, Length: 2549, dtype: object>

In [129]:
d2

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
13    0280-XJGEX    Male              0  ...         103.70      5036.30    Yes
...          ...     ...            ...  ...            ...          ...    ...
7021  1699-HPSBG    Male              0  ...          59.80       727.80    Yes
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7032  6894-LFHLY    Male              1  ...          75.75        75.75    Yes
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes

[1869 rows x 21 columns]

In [130]:
d2[data["gender"] == "Male"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
2     3668-QPYBK   Male              0  ...          53.85       108.15    Yes
13    0280-XJGEX   Male              0  ...         103.70      5036.30    Yes
20    8779-QRDMV   Male              1  ...          39.65        39.65    Yes
22    1066-JKSGK   Male              0  ...          20.15        20.15    Yes
26    6467-CHFZW   Male              0  ...          99.35      4749.15    Yes
...          ...    ...            ...  ...            ...          ...    ...
7009  7703-ZEKEF   Male              0  ...          81.00      1917.10    Yes
7018  1122-JWTJW   Male              0  ...          70.65        70.65    Yes
7021  1699-HPSBG   Male              0  ...          59.80       727.80    Yes
7032  6894-LFHLY   Male              1  ...          75.75        75.75    Yes
7041  8361-LTMKD   Male              1  ...          74.40       306.60    Yes

[930 rows x 21 columns]

Internet service by males based on churn = yes

In [131]:
d8=d2[data["gender"] == "Male"]
d8

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
2     3668-QPYBK   Male              0  ...          53.85       108.15    Yes
13    0280-XJGEX   Male              0  ...         103.70      5036.30    Yes
20    8779-QRDMV   Male              1  ...          39.65        39.65    Yes
22    1066-JKSGK   Male              0  ...          20.15        20.15    Yes
26    6467-CHFZW   Male              0  ...          99.35      4749.15    Yes
...          ...    ...            ...  ...            ...          ...    ...
7009  7703-ZEKEF   Male              0  ...          81.00      1917.10    Yes
7018  1122-JWTJW   Male              0  ...          70.65        70.65    Yes
7021  1699-HPSBG   Male              0  ...          59.80       727.80    Yes
7032  6894-LFHLY   Male              1  ...          75.75        75.75    Yes
7041  8361-LTMKD   Male              1  ...          74.40       306.60    Yes

[930 rows x 21 columns]

In [132]:
d8['InternetService'].value_counts

<bound method IndexOpsMixin.value_counts of 2               DSL
13      Fiber optic
20              DSL
22               No
26      Fiber optic
           ...
7009    Fiber optic
7018    Fiber optic
7021            DSL
7032    Fiber optic
7041    Fiber optic
Name: InternetService, Length: 930, dtype: object>

In [133]:
d2[data["gender"] == "Female"]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
18    4190-MFLUW  Female              0  ...          55.20       528.35    Yes
29    8773-HHUOZ  Female              0  ...          64.70      1093.10    Yes
...          ...     ...            ...  ...            ...          ...    ...
7008  1980-KXVPM  Female              1  ...          75.05       256.25    Yes
7010  0723-DRCLG  Female              1  ...          74.45        74.45    Yes
7011  5482-NUPNA  Female              0  ...          60.40       272.15    Yes
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes

[939 rows x 21 columns]

Internet service by females based on churn = yes

In [134]:
d9=d2[data["gender"] == "Female"]
d9

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
18    4190-MFLUW  Female              0  ...          55.20       528.35    Yes
29    8773-HHUOZ  Female              0  ...          64.70      1093.10    Yes
...          ...     ...            ...  ...            ...          ...    ...
7008  1980-KXVPM  Female              1  ...          75.05       256.25    Yes
7010  0723-DRCLG  Female              1  ...          74.45        74.45    Yes
7011  5482-NUPNA  Female              0  ...          60.40       272.15    Yes
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes

[939 rows x 21 columns]

In [135]:
d9['InternetService'].value_counts

<bound method IndexOpsMixin.value_counts of 4       Fiber optic
5       Fiber optic
8       Fiber optic
18              DSL
29              DSL
           ...
7008    Fiber optic
7010    Fiber optic
7011            DSL
7026            DSL
7034    Fiber optic
Name: InternetService, Length: 939, dtype: object>

5. Total Charges

In [136]:
data["TotalCharges"].describe()

count    7043.000000
mean     2290.520629
std      2274.717686
min        18.800000
25%       402.225000
50%      1400.300000
75%      3808.100000
max      8684.800000
Name: TotalCharges, dtype: float64

5. a. Total Charges based on gender

In [137]:
D1=data[data["gender"] == "Male"]
D1

      customerID gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE   Male              0  ...          56.95      1889.50     No
2     3668-QPYBK   Male              0  ...          53.85       108.15    Yes
3     7795-CFOCW   Male              0  ...          42.30      1840.75     No
6     1452-KIOVK   Male              0  ...          89.10      1949.40     No
9     6388-TABGU   Male              0  ...          56.15      3487.95     No
...          ...    ...            ...  ...            ...          ...    ...
7033  9767-FFLEM   Male              0  ...          69.50      2625.25     No
7035  8456-QDAVC   Male              0  ...          78.70      1495.10     No
7038  6840-RESVB   Male              0  ...          84.80      1990.50     No
7041  8361-LTMKD   Male              1  ...          74.40       306.60    Yes
7042  3186-AJIEK   Male              0  ...         105.65      6844.50     No

[3555 rows x 21 columns]

In [138]:
D1["TotalCharges"].describe()

count    3555.000000
mean     2291.680667
std      2273.095299
min        18.800000
25%       399.275000
50%      1406.000000
75%      3778.100000
max      8684.800000
Name: TotalCharges, dtype: float64

In [139]:
D2=data[data["gender"] == "Female"]
D2

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
...          ...     ...            ...  ...            ...          ...    ...
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7036  7750-EYXWZ  Female              0  ...          60.65       743.30     No
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No

[3488 rows x 21 columns]

In [140]:
D2["TotalCharges"].describe()

count    3488.000000
mean     2289.338308
std      2276.695359
min        18.850000
25%       403.300000
50%      1389.050000
75%      3834.062500
max      8672.450000
Name: TotalCharges, dtype: float64

5. b. Total Charges based on contract

In [141]:
D3=data[data["Contract"]=="Month-to-month"]
D3

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
6     1452-KIOVK    Male              0  ...          89.10      1949.40     No
...          ...     ...            ...  ...            ...          ...    ...
7033  9767-FFLEM    Male              0  ...          69.50      2625.25     No
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7035  8456-QDAVC    Male              0  ...          78.70      1495.10     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes

[3875 rows x 21 columns]

In [142]:
D3["TotalCharges"].describe()

count    3875.000000
mean     1369.254581
std      1613.879008
min        18.850000
25%       160.100000
50%       679.550000
75%      2066.500000
max      8061.500000
Name: TotalCharges, dtype: float64

In [143]:
D4=data[data["Contract"]=="Two year"]
D4

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
11    7469-LKBCI    Male              0  ...          18.95       326.80     No
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
17    9959-WOFKT    Male              0  ...         106.70      7382.25     No
23    3638-WEABW  Female              0  ...          59.90      3505.10     No
28    5248-YGIJN    Male              0  ...          90.25      6369.45     No
...          ...     ...            ...  ...            ...          ...    ...
7017  4807-IZYOZ  Female              0  ...          20.65      1020.75     No
7019  9710-NJERN  Female              0  ...          20.15       826.00     No
7028  9281-CEDRU  Female              0  ...          64.10      4326.25     No
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[1695 rows x 21 columns]

In [144]:
D4["TotalCharges"].describe()

count    1695.000000
mean     3746.752383
std      2582.454154
min        20.350000
25%      1280.125000
50%      3638.250000
75%      6044.300000
max      8672.450000
Name: TotalCharges, dtype: float64

In [145]:
D5=data[data["Contract"]=="One year"]
D5

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
9     6388-TABGU    Male              0  ...          56.15      3487.95     No
12    8091-TTVAX    Male              0  ...         100.35      5681.10     No
16    8191-XWSZG  Female              0  ...          20.65      1022.95     No
...          ...     ...            ...  ...            ...          ...    ...
7022  7203-OYKCT    Male              0  ...         104.95      7544.30     No
7031  3605-JISKB    Male              1  ...          60.00      3316.10     No
7036  7750-EYXWZ  Female              0  ...          60.65       743.30     No
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No

[1473 rows x 21 columns]

In [146]:
D5["TotalCharges"].describe()

count    1473.000000
mean     3038.377461
std      2233.477741
min        18.800000
25%       989.450000
50%      2658.400000
75%      4860.350000
max      8684.800000
Name: TotalCharges, dtype: float64

5. c. Total Charges based on payment method

In [147]:
data["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [148]:
D6=data[data["PaymentMethod"]=="Electronic check"]
D6

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
14    5129-JLPIS    Male              0  ...         105.50      2686.05     No
...          ...     ...            ...  ...            ...          ...    ...
7023  1035-IPQPU  Female              1  ...         103.50      6479.40     No
7029  2235-DWLJU  Female              1  ...          44.40       263.05     No
7032  6894-LFHLY    Male              1  ...          75.75        75.75    Yes
7036  7750-EYXWZ  Female              0  ...          60.65       743.30     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No

[2365 rows x 21 columns]

In [81]:
D6["TotalCharges"].describe()

count    2365.000000
mean     2090.868182
std      2155.435320
min        18.850000
25%       308.050000
50%      1253.900000
75%      3340.550000
max      8564.750000
Name: TotalCharges, dtype: float64

In [149]:
D7=data[data["PaymentMethod"]=="Mailed check"]
D7

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
10    9763-GRSKD    Male              0  ...          49.95       587.45     No
16    8191-XWSZG  Female              0  ...          20.65      1022.95     No
...          ...     ...            ...  ...            ...          ...    ...
7019  9710-NJERN  Female              0  ...          20.15       826.00     No
7027  0550-DCXLH    Male              0  ...          73.35       931.55     No
7030  0871-OPBXW  Female              0  ...          20.05        39.25     No
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes

[1612 rows x 21 columns]

In [150]:
D7["TotalCharges"].describe()

count    1612.000000
mean     1083.236973
std      1509.101844
min        18.800000
25%       116.937500
50%       473.675000
75%      1316.000000
max      8476.500000
Name: TotalCharges, dtype: float64

In [151]:
D8=data[data["PaymentMethod"]=="Bank transfer (automatic)"]
D8

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
9     6388-TABGU    Male              0  ...          56.15      3487.95     No
13    0280-XJGEX    Male              0  ...         103.70      5036.30    Yes
17    9959-WOFKT    Male              0  ...         106.70      7382.25     No
21    1680-VDCWW    Male              0  ...          19.80       202.25     No
...          ...     ...            ...  ...            ...          ...    ...
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7028  9281-CEDRU  Female              0  ...          64.10      4326.25     No
7035  8456-QDAVC    Male              0  ...          78.70      1495.10     No
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[1544 rows x 21 columns]

In [152]:
D8["TotalCharges"].describe()

count    1544.000000
mean     3083.566023
std      2360.362773
min        19.250000
25%      1052.387500
50%      2479.500000
75%      4948.337500
max      8684.800000
Name: TotalCharges, dtype: float64

In [153]:
D9=data[data["PaymentMethod"]=="Credit card (automatic)"]
D9

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
6     1452-KIOVK    Male              0  ...          89.10      1949.40     No
11    7469-LKBCI    Male              0  ...          18.95       326.80     No
12    8091-TTVAX    Male              0  ...         100.35      5681.10     No
15    3655-SNQYZ  Female              0  ...         113.25      7895.15     No
18    4190-MFLUW  Female              0  ...          55.20       528.35    Yes
...          ...     ...            ...  ...            ...          ...    ...
7024  7398-LXGYX    Male              0  ...          84.80      3626.35     No
7031  3605-JISKB    Male              1  ...          60.00      3316.10     No
7033  9767-FFLEM    Male              0  ...          69.50      2625.25     No
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No

[1522 rows x 21 columns]

In [154]:
D9["TotalCharges"].describe()

count    1522.000000
mean     3074.920894
std      2410.536742
min        19.300000
25%       989.400000
50%      2454.175000
75%      5016.550000
max      8670.100000
Name: TotalCharges, dtype: float64